### ISSUE TITLE
Not taking into account countys

### ISSUE THREAD

**Issue by knutta** [paphko/mmm-weatherchart#1]
The module is working perfectly for your example city. However in some cases the cities are divided into a few more categories, as is the case for both Oslo, Trondheim and Bergen. For these cities  - and probably a few more - the module is not working. Is it a quick fix for this?

**Comment by paphko** [comment]
Please give an example of your url?

**Comment by knutta** [comment]
Sure:
Www.yr.no/place/Norway/Sør-Trøndelag/Trondheim/Trondheim
Www.yr.no/place/Norway/Oslo/oslo/oslo
Www.yr.no/place/Norway/Hordaland/Bergen/Bergen

**Comment by paphko** [comment]
Then please try as area: Sør-Trøndelag/Trondheim, Oslo/oslo, or Hordaland/Bergen

**Comment by knutta** [comment]
Nope.. No joy..

**Comment by paphko** [comment]
This works for me. Please note that the values are case sensitive.

config: {
  country: 'Norway',
  area: 'Oslo/oslo',
  city: 'oslo',
  hideBorder: false,
  updateInterval: 33 * 60 * 1000,
}

**Comment by spectroman** [comment]
hi, does this change between '?' to '#' works for you? I found out that he will simple not update, if changed to '#', whilst using '?' will break the image.

As such, I've built a more complete solution that works. So far I'm running it locally on my MM, I will attach the solution here.

[mmm-weatherchart.js.gz](https://github.com/paphko/mmm-weatherchart/files/1172215/mmm-weatherchart.js.gz)
[node_helper.js.gz](https://github.com/paphko/mmm-weatherchart/files/1172214/node_helper.js.gz)

Then u decide if u can use to update ur official repo.

**Comment by paphko** [comment]
@spectroman thank you for your suggestion. You are right, using a '#' does not work.
Would you mind creating a pull request for your changes against my repo?
Btw, I accidently referenced this issue in my commit, but it should rather be #5.

**Comment by spectroman** [comment]
Hi Paphko,
I see you already took care to make the amendments, is cool! For me would be a bit difficult to find time around to work on it this week... i'm almost on holiday and the agenda is full!
I had implemented the changes and did not took into consideration some stuff that could be a variable using in my implementation mostly hard coded stuff.. (like the location to download the file...) 
I see you took care of that.. So I will not make any changes on the repo, as you already took charge :)
I really like you module, it would be a shame if we didn't fix him! ;-)
Cheers!


Julio C. Hegedus v.41.7
---------------------------------------------------------------------
Novell Netware & Linux Specialist
https://www.juliochegedus.info
ICQ: 3614823
Skype: brclimber
CAP #.: 928


On Tuesday, July 25, 2017, 8:28:41 PM GMT+2, paphko <notifications@github.com> wrote:


@spectroman thank you for your suggestion. You are right, using a '#' does not work.
Would you mind creating a pull request for your changes against my repo?
Btw, I accidently referenced this issue in my commit, but it should rather be #5.

**Comment by FritsBolt** [comment]
Hi 
Just installed everything Works fine except that no chart is published on nog screen. The SVG is saved in the cache directory but not shown
I could USD any help
Kind regard Frits

**Comment by FritsBolt** [comment]
USD = use ( f*k the doellchecker)

**Comment by paphko** [comment]
Hi Frits, it should be a png, not svg.
Please check your log for suspicious entries, both server and browser. Please try with another browser, e.g. with another computer.

**Comment by FritsBolt** [comment]
Thanks it Works fine!


________________________________
Van: paphko <notifications@github.com>
Verzonden: dinsdag, februari 5, 2019 7:14 AM
Aan: paphko/mmm-weatherchart
CC: FritsBolt; Comment
Onderwerp: Re: [paphko/mmm-weatherchart] Not taking into account countys (#1)


Hi Frits, it should be a png, not svg.
Please check your log for suspicious entries, both server and browser. Please try with another browser, e.g. with another computer.
