### ISSUE TITLE
Forecast widget is being replaced

### ISSUE THREAD

**Issue by MajorC1983** [paphko/mmm-weatherchart#19]
Hi,
the forecast widget seams to be replaced by a new one. At least that is what I see on my mm at the moment.

https://developer.yr.no/doc/guides/deprecating-old-widgets/

**Comment by paphko** [comment]
Hmm, indeed. But it seems as if we could adjust the code (and of course the config) to use the new svg, like this one from berlin: https://www.yr.no/nb/innhold/2-2950159/meteogram.svg

Currently I'm not able to test this, may in one or two weeks. Shouldn't be too hard to do this, maybe someone of you wants to give it a try?

**Comment by paphko** [comment]
The 'en' segment seems to be the language, 'content' or 'innehold' a language-specific path, and the numbers some code for the location.
I would suggest to reduce the configuration to the entire path in url:
  locationPath = 'en/content/2-2950159/meteogram.svg'

This is easier for the user (copy path from 'svg'-link) and more robust in case the format changes again.

@cyberdie would you mind to create a PR for this? :)
