### ISSUE TITLE
Show graph in colors

### ISSUE THREAD

**Issue by BlueForrest** [paphko/mmm-weatherchart#21]
Module is working fine, 

Sorry for the misunderstanding - colors can be achieved by option negativeImage.   I should have read the docu first before asking a question

**Comment by mrhawkin** [comment]
negativeImage=true will make the image grayscale. =fasle Wille give color but also white background.
I have made a fork that will give black background but keep the color of the icons and graph:
https://github.com/mrhawkin/mmm-weatherchart
