### ISSUE TITLE
Blank images due to redirect

### ISSUE THREAD

**Issue by marcuswillberg** [paphko/mmm-weatherchart#25]
The weather information has stopped working for me since a few days back. Testing URL from logs manually with wget it seems that the content is now only served after redirect to Azure:
```
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://yr-external-content-prod.ne.yr.azure.nrk.cloud/en/meteogram/...
```

This redirect is not followed by Node.js, so the cached image downloaded by module consists of this data:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by BottomNine** [comment]
Having same issue since last week. Any luck?

**Comment by matkovic** [comment]
It looks like yr.no enforced https on their page. The solution that is working for me is to change the first line in node_helper.js from
`var http = require('http');`
to
`var http = require('https');`

The http tries to access to 80 port which is not accessible anymore (or is being redirected), whereas https module goes directly to port 443.

If it works for you, I (or someone else) can PR this fix

**Comment by Jupter1** [comment]
> If it works for you, I (or someone else) can PR this fix

It works for me as well. Thanks a lot!

**Comment by BottomNine** [comment]
Dang, doesnt seem to be working for me. May try and re-install module and try that fix.

**Comment by Jupter1** [comment]
#26 
I have made a pull request.

**Comment by marcuswillberg** [comment]
Thanks @Jupter1 , this fix worked for me as well.
