### ISSUE TITLE
Add custom CSS colors

### ISSUE THREAD

**Issue by Labzz** [paphko/mmm-weatherchart#3]
Can you make is possible to change CSS with colors for the Sun, rain, storm etc icons? A good example is shown in the example from yr itself. [https://www.yr.no/place/Netherlands/North_Holland/Amsterdam/external_box_hour_by_hour.html](url)

**Comment by paphko** [comment]
I agree that different colors would be nice.
Unfortunately, it is an image with a filter that shows a negative of the original (that you have linked).
With this approach, it is not possible to change colors.
