### ISSUE TITLE
mmm-weatherchart causes Magic Mirror to stop working

### ISSUE THREAD

**Issue by philipvanv** [paphko/mmm-weatherchart#6]
Hello,

For some reason, your module causes my Magic Mirror to stop working. It results in a screen with an error saying the localhost couln't be loaded and that the connection is refused.
I use a Raspberry Pi Zero Wireless where I installed Magic Mirror using this procedure;
https://forum.magicmirror.builders/topic/2075/magicmirror-on-pi-zero-w

Do you have an idea what's happening?

Best regards,

Philip

**Comment by paphko** [comment]
Nope. Please provide more information. Logs from MM and logs from browser would be helpful for debugging.

**Comment by philipvanv** [comment]
Sorry for my late response. 
I went for an other module that did work on my system, due to a lack of time to figure the problem out. 
Your module looks great and maybe I'll try again later when I have more time. If you want, you can delete this issue.
