### ISSUE TITLE
Unknown letter for link

### ISSUE THREAD

**Issue by sciflo** [paphko/mmm-weatherchart#7]
For my hometown Mannheim the link is built up as followed:
https://www.yr.no/place/Germany/Baden-Württemberg/Mannheim/
As you can see the link includes the letter ü, which is not possible for the script to download from. Rather the script tries to download from:
https://www.yr.no/place/Germany/Baden-W???rttemberg/Mannheim/meteogram.png

Is there a way to fix this letter issue?

**Comment by paphko** [comment]
Just a guess, try: https://www.yr.no/place/Germany/Baden-W%C3%BCrttemberg/Mannheim/

**Comment by paphko** [comment]
@sciflo does it work?

**Comment by sciflo** [comment]
I tried and it worked. Thanks for the fast support.
You created a very cool module!
